command:
  - streamlit
  - run
  - app.py
  - --server.address=0.0.0.0
  - --server.port=8000

env:
  - name: GENIE_SPACE_ID
    valueFrom: genie-space
  - name: STREAMLIT_GATHER_USAGE_STATS
    value: "false"

permissions:
  scopes:
    - sql
    - dashboards.genie