command:
  - streamlit
  - run
  - app.py
env:
  - name: GENIE_SPACE_ID
    valueFrom: genie-space
  - name: DATABRICKS_HOST
    value: "https://adb-8187118582959821.1.azuredatabricks.net"
  - name: DATABRICKS_TOKEN
    valueFrom: secret
